version: "3.7"
services:
  jupyterlab:
    build: .
    container_name: jupyterlab
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - $PWD/work:/home/jovyan/work
      - $PWD/library:/home/jovyan/lib/R/library
    cap_drop:
      - CAP_NET_RAW
    security_opt:
      - no-new-privileges
    command: start.sh jupyter lab --NotebookApp.token=''